baseurl                 = "https://www.mateoconlechuga.com/"
DefaultContentLanguage  = "en"
title                   = "mateoconlechuga"
theme                   = ["hugo-future-imperfect-slim"]
paginate                = 4
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[module]
  [module.hugoVersion]
  extended              = true
  min                   = "0.62.0"

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = []
  hideEmptyStats        = false
  toc                   = true
  tocWords              = 1000

  [params.meta]
    description         = "MateoConLechuga's Adventure Site"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "mateoconlechuga"
    dynamicTitles       = false
    searchMenu          = false
    shareMenu           = false
    languageMenu        = false

  [params.intro]
    header                = "MateoConLechuga"
    paragraph             = "Let's go on an adventure"
    rssIntro              = false
    socialIntro           = true
    hideWhenSingleColumn  = true
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/moscow.webp"
      shape               = "circle"
      width               = ""
      alt                 = ""

  [params.sidebar]
    about               = ""
    postAmount          = 8
    categories          = false
    categoriesByCount   = false

  [params.footer]
    rssFooter           = false
    socialFooter        = false

  [params.utterances]
    enabled             = false
    repo                = "mateoconlechuga/blog"
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = "comment"
    theme               = "github-light"

  [params.giscus]
    enabled             = true
    repo                = "mateoconlechuga/blog"
    repoId              = "R_kgDOIr1lWA"
    category            = "Comment"
    categoryId          = "DIC_kwDOIr1lWM4CTSel"

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 5

[social]
  # Coding Communities
  github                = "mateoconlechuga"
  gitlab                = ""
  stackoverflow         = "5455966" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "matthew-ryan-waltz"
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = ""
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = ""
